import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { once } from 'node:events';
import crypto from 'node:crypto';
const root = path.resolve(new URL('..', import.meta.url).pathname);

test('quotation client creation: duplicate protection and permissions', {timeout:60000}, async t => {
  const data = await fs.mkdtemp(path.join(os.tmpdir(),'ftw-update-api-'));
  const probe=net.createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(r=>probe.close(r));
  const password=crypto.randomUUID();
  const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,FTW_DATA_DIR:data,FTW_STORAGE:'json',PORT:String(port),FTW_ADMIN_PASSWORD:password},stdio:['ignore','pipe','pipe']});
  let log='';child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
  t.after(async()=>{if(child.exitCode===null){child.kill('SIGTERM');await once(child,'exit');}await fs.rm(data,{recursive:true,force:true});});
  const base='http://127.0.0.1:'+port;
  let ready=false;
  for(let i=0;i<200;i++){if(child.exitCode!==null)throw Error(log);try{if((await fetch(base+'/api/version')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}
  assert(ready,log);
  const get=async(p,user)=>fetch(base+p,{headers:user?{Authorization:'Bearer '+user.token}:{}});
  const post=async(p,body,user)=>fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json',...(user?{Authorization:'Bearer '+user.token}:{})},body:JSON.stringify(body)});
  const admin=await (await post('/api/login',{username:'admin',password})).json();
  await post('/api/users',{username:'sales',password,role:'sales'},admin);
  const sales=await (await post('/api/login',{username:'sales',password})).json();
  const q=await (await post('/api/quotations',{clientName:'New Customer',contactName:'Alice'},sales)).json();
  assert.equal((await post('/api/clients/from-quotation',{company:'x'})).status,401);
  assert.equal((await post('/api/clients/from-quotation',{company:'x',owner:admin.id},sales)).status,403);
  assert.equal((await post('/api/clients/from-quotation',{company:' '},sales)).status,400);
  const requests=Array.from({length:5},()=>post('/api/clients/from-quotation',{company:' New Customer ',contactName:'Alice',country:'智利',owner:sales.id,quoteId:q.id},sales));
  const responses=await Promise.all(requests);assert.equal(responses.filter(r=>r.status===201).length,1);assert.equal(responses.filter(r=>r.status===200).length,4);
  const results=await Promise.all(responses.map(r=>r.json()));assert.equal(new Set(results.map(r=>r.client.id)).size,1);assert.equal(results[0].client.contactName,'Alice');assert.equal(results[0].client.country,'智利');
  const existing=await (await post('/api/clients/from-quotation',{company:'new customer',contactName:'Do not overwrite'},sales)).json();assert.equal(existing.created,false);assert.equal(existing.client.contactName,'Alice');
  const foreignQ=await (await post('/api/quotations',{clientName:'Foreign'},admin)).json();
  assert.equal((await post('/api/clients/from-quotation',{company:'Foreign',quoteId:foreignQ.id},sales)).status,403);
  await post('/api/clients',{company:'Private Company'},admin);
  const own=await (await post('/api/clients/from-quotation',{company:'Private Company'},sales)).json();assert.equal(own.created,true);assert.equal(own.client.owner,sales.id);
  assert.equal((await (await get('/api/clients',sales)).json()).length,2);
});
